#!/bin/bash
# Generate walker omarchy-dynamic style.css with colors embedded directly

COLORS="$HOME/.config/omarchy/current/theme/colors.toml"
STYLE="$HOME/.config/walker/themes/omarchy-dynamic/style.css"

[[ -f "$COLORS" ]] || exit 0

get_color() {
  grep -m1 "^$1 *= *" "$COLORS" | sed 's/.*= *"\(.*\)".*/\1/'
}

accent=$(get_color "accent")
foreground=$(get_color "foreground")
background=$(get_color "background")
color0=$(get_color "color0")
color7=$(get_color "color7")
color8=$(get_color "color8")

cat > "$STYLE" <<EOF
/* Generated by Omarchy — do not edit directly */

* {
  all: unset;
  font-family: 'JetBrainsMono Nerd Font', monospace;
  font-size: 14px;
  color: $foreground;
}

window, .window { background: transparent; }

.box-wrapper {
  background: alpha($background, 0.85);
  border-radius: 16px;
  border: 1px solid alpha($accent, 0.4);
  box-shadow: 0 8px 32px alpha($color0, 0.8);
  padding: 12px;
}

.search-container {
  background: $background;
  padding: 8px 8px 4px;
  border-radius: 12px 12px 0 0;
}

.input, entry {
  background: $color0;
  color: $foreground;
  border: 1px solid alpha($accent, 0.3);
  border-radius: 10px;
  padding: 10px 14px;
  caret-color: $accent;
  font-size: 15px;
}

.input:focus, entry:focus {
  border-color: $accent;
  background: $color8;
}

.input placeholder, entry placeholder {
  color: $color8;
  opacity: 1;
}

.content-container, .scroll, scrolledwindow, viewport {
  background: $background;
  border-radius: 0 0 12px 12px;
}

listview { background: transparent; padding: 4px 0; }

child, row {
  background: transparent;
  border-radius: 8px;
  padding: 4px 6px;
  transition: background 100ms ease;
}

child:hover, row:hover { background: $color0; }

child:selected, row:selected { background: alpha($accent, 0.15); }

.item-box {
  padding: 10px 14px;
  border-radius: 8px;
}

child:hover .item-box { background: transparent; }

child:selected .item-box {
  background: alpha($accent, 0.35);
  border-radius: 8px;
}

child:selected .item-box * { color: $foreground; }

.item-text, .item-text-box {
  all: unset;
  padding: 6px 0;
  color: $foreground;
  font-size: 16px;
}

.item-subtext {
  font-size: 13px;
  color: $color7;
  min-height: 0;
  margin: 0;
  padding: 0;
}

.item-image, image {
  margin-right: 14px;
  border-radius: 6px;
  -gtk-icon-size: 28px;
}

.normal-icons { -gtk-icon-size: 28px; }
.large-icons  { -gtk-icon-size: 40px; }

scrollbar { background: transparent; opacity: 0; }
scrollbar slider {
  background: $color8;
  border-radius: 4px;
  min-width: 4px;
}
EOF
