# Background and foreground colors
background = #08030A
foreground = #EEF1F4

# Standard colors
palette = 0=#08030A
palette = 1=#a26f69
palette = 2=#64834a
palette = 3=#E9DE00
palette = 4=#617dbe
palette = 5=#7177c0
palette = 6=#7EABAA
palette = 7=#EEF1F4

# Bright colors
palette = 8=#6a666b
palette = 9=#cc9189
palette = 10=#84aa5d
palette = 11=#fbee00
palette = 12=#839ff3
palette = 13=#9598f5
palette = 14=#9fd2d1
palette = 15=#d6eeff
