background            #08030A
foreground            #EEF1F4

# black
color0  #08030A
color8  #6a666b

# red
color1  #a26f69
color9  #cc9189

# green
color2  #64834a
color10 #84aa5d

# yellow
color3  #E9DE00
color11 #fbee00

# blue
color4  #617dbe
color12 #839ff3

# magenta
color5  #7177c0
color13 #9598f5

#cyan
color6  #7EABAA
color14 #9fd2d1

#white
color7  #EEF1F4
color15 #d6eeff


