[colors.primary]
background = "#0c0b0c"
foreground = "#FAFCFB"

[colors.cursor]
text = "#0c0b0c"
cursor = "#e2dddc"

[colors.vi_mode_cursor]
text = "#0c0b0c"
cursor = "#e2dddc"

[colors.search.matches]
foreground = "#0c0b0c"
background = "#6B5E73"

[colors.search.focused_match]
foreground = "#0c0b0c"
background = "#c38b7b"

[colors.footer_bar]
foreground = "#0c0b0c"
background = "#FAFCFB"

[colors.selection]
text = "#0c0b0c"
background = "#FAFCFB"

[colors.normal]
black = "#0c0b0c"
red = "#c38b7b"
green = "#87a9b0"
yellow = "#6B5E73"
blue = "#b59790"
magenta = "#c4d8e2"
cyan = "#a5a0b6"
white = "#cfd3cd"

[colors.bright]
black = "#584e51"
red = "#c38b7b"
green = "#87a9b0"
yellow = "#6B5E73"
blue = "#b59790"
magenta = "#c4d8e2"
cyan = "#a5a0b6"
white = "#e2dddc"
