# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

monitor = DP-1, 2560x1440@144, 0x0, 1
monitor = HDMI-A-2, 3840x2160@120, 2560x0, 1

general {
    col.active_border = rgb(bf7fff)
    col.inactive_border = rgb(6b4080)
}

exec-once = sleep 2 && steam -silent

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu