/* Walker color variables — generated by Omarchy. Do not edit directly. */
@define-color accent     {{ accent }};
@define-color mauve      {{ accent }};
@define-color lavender   {{ accent }};
@define-color text       {{ foreground }};
@define-color subtext0   {{ color7 }};
@define-color foreground {{ foreground }};
@define-color background {{ background }};
@define-color base       {{ background }};
@define-color mantle     {{ color0 }};
@define-color crust      {{ color0 }};
@define-color surface0   {{ color0 }};
@define-color surface1   {{ color8 }};
@define-color surface2   {{ color8 }};
@define-color overlay0   {{ color8 }};
@define-color border     {{ accent }};
@define-color selected-text {{ accent }};
