/* Generated by Omarchy — edit ~/.config/omarchy/themed/waybar-theme.css.tpl */

@define-color bar-bg      rgba(0, 0, 0, 0);
@define-color main-bg     {{ background }};
@define-color main-fg     {{ foreground }};

@define-color wb-act-bg   {{ color7 }};
@define-color wb-act-fg   {{ background }};

@define-color wb-hvr-bg   {{ accent }};
@define-color wb-hvr-fg   {{ background }};

@define-color col-cpu      {{ color4 }};
@define-color col-mem      {{ color2 }};
@define-color col-temp     {{ color3 }};
@define-color col-disk     {{ color3 }};
@define-color col-net      {{ color6 }};
@define-color col-audio    {{ color5 }};
@define-color col-date     {{ accent }};
@define-color col-warn     {{ color3 }};
@define-color col-crit     {{ color1 }};
@define-color col-update   {{ color2 }};
@define-color col-rec      {{ color1 }};
@define-color col-muted    {{ color8 }};
@define-color col-sub      {{ color7 }};
@define-color col-mauve    {{ accent }};
@define-color col-base     {{ background }};
@define-color col-mantle   {{ background }};
@define-color col-surface1 {{ color0 }};
